// Copyright (C) 2026 Neon Law Foundation.
// SPDX-License-Identifier: Apache-2.0

/**
 * The full text of every opinion in `src/research/opinions/`, bundled.
 *
 * `import.meta.glob` reads the Markdown at build time, so the portal serves the
 * opinions from its own mount with no fetch, no API, and nothing off-origin —
 * which is the same property `src/test/bundle.test.ts` asserts about every other
 * asset here. It also means the text cannot drift from the repository: what a
 * reader expands is the file that is checked in beside it.
 *
 * The cost is honest and worth naming: these eleven opinions are roughly 340 kB
 * of prose, and all of it lands in the JavaScript bundle. A portal carrying a
 * whole reporter would fetch instead — but it would then need a route, a cache,
 * and a story for what happens when that route 404s, which is a great deal of
 * machinery for a sample that has eleven files.
 *
 * The Markdown is generated by `src/research/convert.py` from the CAP JSON beside
 * it. Nothing in that folder is edited by hand.
 */

const SOURCES = import.meta.glob<string>('./research/opinions/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
})

/**
 * One opinion's Markdown, by file stem, or `null` when it is not bundled.
 *
 * A missing file is a real possibility — the index in `research.ts` is written
 * by hand and the folder is filled by a script — so this reports the absence
 * rather than throwing. The caller says so on the page instead of blanking it.
 */
export function opinionMarkdown(file: string): string | null {
  const path = Object.keys(SOURCES).find((candidate) => candidate.endsWith(`/${file}.md`))
  return path ? (SOURCES[path] ?? null) : null
}
